#!/usr/bin/perl
use strict;
use warnings;

# This is .git/COMMIT_EDITMSG
my @INPUT_FILE = @ARGV;

# Commit type define in this repo
my @type_list =
  qw(build ci docs feat fix perf refactor style test revert merge);
my @scope_list = qw(ssd pcie);

open( my $fh, "<", @INPUT_FILE )
  or die "can not open";

exit 1;
