/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "/home/baopang/source_code/bios/toolbox/test/test_io_lib.check" instead.
 */

#include <check.h>

#line 1 "/home/baopang/source_code/bios/toolbox/test/test_io_lib.check"
#include <debug_lib.h>
#include <io_lib.h>

#include <inttypes.h>

START_TEST(init)
{
#line 7
rw_config *cfg = malloc(sizeof(rw_config));
char *arr[] = { "0x600", "0x24" };
cfg->address = 0x0;
cfg->data = 0x0;
cfg->mode = io;
cfg->width = io_width_8;
cfg->is_address_setted = false;
cfg->is_data_setted = false;
cfg->init = rw_config_init;
cfg->print = rw_config_print;
cfg->format = "0x%" PRIxMAX "\n";

cfg->init(cfg, arr);
fail_unless(cfg->is_address_setted == true);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, init);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
