#ifndef _OEM_HMRFPO_ENABLE_H
#define _OEM_HMRFPO_ENABLE_H

EFI_STATUS  CheckMEResponse(UINT64 HECI_BAR64);
VOID    ResetQueue(UINT64 HECI_BAR64);
VOID    SendHMRFPOMessageToME(UINT64 HECI_BAR64);

#endif // _OEM_HMRFPO_ENABLE_H
